### ISSUE TITLE
App doesnt work when given a name with special characters

### ISSUE THREAD

**Issue by jvsg** [manu-chroma/username-availability-checker#7]
1. When given a name with slash in between, The app keeps loading on forever
2. When given a name with # in between , the app only considers the letters before # for checking the    availability.
3. Some sites do not allow the names with special characters. So appropriate arrangement should be made within the software.

**Comment by Manu-chroma** [comment]
1. '/' and '#' are not permitted character in the username. I'll take care of them and other such characters in the js code.

2. Reg your 3rd issue, yes the API technically doesn't acknowledge individual username restrictions of each of the website. I'll see if there can be any workaround for that instead of brute forcing logic for every website.

**Comment by gyanl** [comment]
Perform a sanity check on the data when it's entered, and show an error if there's a special character in there?

**Comment by Asuza** [comment]
I would like to work on this issue, if possible.

Though, does it still work as expected, when *not* using a special character? For example, visiting https://username-availabilty.herokuapp.com/check/twitter.com/bobsaget returns a 200 status code.

A 200 status code means the name is available, right? Though [bobsaget](https://twitter.com/bobsaget) is definitely taken.

**Comment by manu-chroma** [comment]
@Asuza This is the code from the final page which is rendered: https://github.com/manu-chroma/username-availability-checker/blob/master/flask/templates/world.html#L29

Should make things clearer. :) You're welcome to work on this issue
